#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh --hack
xsetroot -cursor_name left_ptr

