#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias wifi='nmtui'
alias size='df -h'
alias h='htop'
alias r='ranger'
alias n='neofetch'
alias s='bash ~/.scrollbook/search_packages.sh'
alias programlist='sudo pacman -Qeq'
alias update='bash ~/.scrollbook/updateNclean.sh'
alias just_remove_orphans='bash ~/.scrollbook/remove_package_orphans.sh'

PS1='[\u@\h \W]\$ '
