#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias update='bash ~/.scrollbook/updateNclean.sh'
alias prepare='bash ~/.scrollbook/prepare.sh'
alias audio='bash ~/.scrollbook/ytdl-audio.sh'
alias video='bash ~/.scrollbook/ytdl-video.sh'

PS1='[\u@\h \W]\$ '
