#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias update='bash ~/Atina/scrollbook/uadc.sh'
alias wifi='nmtui'
alias bat='acpi'
alias h='htop'
alias size='df -h'
alias programlist='sudo pacman -Qeq'
alias audio='bash ~/Atina/scrollbook/ytdl-audio.sh'
alias video='bash ~/Atina/scrollbook/ytdl-video.sh'

PS1='[\u@\h \W]\$ '
